Fix tombstone forward reference
Fixes:

```
ConfigError: field "cluster" not yet prepared so type is still a ForwardRef, you might need to call TombstoneIncludes.update_forward_refs().
```

Also drop future annotations to not silence undefined name errors in the future.